import type { BoardDocument } from "@/domain/board/board-document";

export const sampleBoard: BoardDocument = {
  version: 1,
  id: "board:backend-learning",
  name: "Backend Learning",
  elements: [
    {
      id: "element:backend",
      kind: "rectangle",
      x: 220,
      y: 210,
      width: 300,
      height: 150,
      text: "Backend\nRequests · business logic · data",
      color: "violet",
    },
    {
      id: "element:frontend",
      kind: "rectangle",
      x: 680,
      y: 90,
      width: 240,
      height: 120,
      text: "Frontend\nReact · Next.js",
      color: "blue",
    },
    {
      id: "element:api",
      kind: "rectangle",
      x: 680,
      y: 340,
      width: 240,
      height: 120,
      text: "API Server\nValidation · authorization",
      color: "green",
    },
    {
      id: "element:question",
      kind: "note",
      x: 240,
      y: 480,
      width: 220,
      height: 220,
      text: "Question\nHow is an API different from a backend?",
      color: "yellow",
    },
    {
      id: "element:hint",
      kind: "text",
      x: 580,
      y: 560,
      width: 320,
      height: 80,
      text: "Connect ideas, move them around, then undo the change.",
      color: "grey",
    },
  ],
  connections: [],
};
